name: Deploy Frontend to chronicling-america-fe

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set environment variable
        run: |
          echo "VITE_C_BASE_PORT=${{ secrets.VITE_C_BASE_PORT }}" >> $GITHUB_ENV
          echo "VITE_C_BASE_URL=${{ secrets.VITE_C_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_C_ENV=${{ secrets.VITE_C_ENV }}" >> $GITHUB_ENV
          echo "VITE_C_HOST=${{ secrets.VITE_C_HOST }}" >> $GITHUB_ENV

      - name: Install dependencies and build
        working-directory: frontend
        run: |
          npm install
          npm run build-git

      - name: Deploy to chronicling-america-fe repository
        env:
          DEPLOY_REPO: glebovanton/chronicling-america-fe
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Clone the target repository
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${DEPLOY_REPO}.git deploy-repo
          cd deploy-repo

          # Remove old files in the root (if needed)
          rm -rf *

          # Copy new build files
          cp -R ../frontend/dist/* .

          # Push changes to target repository
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy build files"
          git push
